### ISSUE TITLE
For those, who searching download link

### ISSUE THREAD

**Issue by tyuop077** [CraftMinecraft/MoveMeNow#2]
**Use this download link instead:** 
[Download from Web Archive](https://web.archive.org/web/20190817054559/http://dl.cmc.im/MoveMeNow/movemenow-1.2-17.jar)

**Comment by roblabla** [comment]
Thanks for notifying me of the broken download link! I uploaded the webarchived MoveMeNow and IPWhitelist on SpigotMC.
