### ISSUE TITLE
Feature request: multiple fallback servers for different kick messages

### ISSUE THREAD

**Issue by comendantmc** [CraftMinecraft/MoveMeNow#4]
It would be great to be able to set multiple fallback servers for different kick messages.
For example if the server reboots it kicks with "reboot" message the plugin redirects to the server for waiting. After the main server is rebooted the server for waiting kicks with another message and the plugin redirects players to the auth server

**Comment by roblabla** [comment]
MoveMeNow is currently unmaintained, due to lack of time. I won't be adding any new features myself. That said, if someone wants to implement this and make a PR, I will gladly merge it, and we can discuss passing over the plugin maintenance.

**Comment by comendantmc** [comment]
Thanks for answering. I'm gonna try to implement this and make a PR myself then
