### ISSUE TITLE
Please fix for FlameCord

### ISSUE THREAD

**Issue by GWServer** [CraftMinecraft/MoveMeNow#9]
Please fix for FlameCord (BungeeCord protection from Netty) FlameCord disconnects the player from the server in another way, which causes MoveMeNow to falsely move the player to the lobby who has already left the server.
https://github.com/2lstudios-mc/FlameCord/releases

**Comment by roblabla** [comment]
This plugin is more-or-less abandonned, as I don't play or work on minecraft anymore. If you submit a PR, I will gladly merge it and publish a new release though.

**Comment by GWServer** [comment]
what is PR?

**Comment by roblabla** [comment]
A [Pull Request](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests).

**Comment by GWServer** [comment]
The problem has already been solved. It turned out that your plugin checks the reason even for those who left the server. I want to thank you for your answers and for a nice plugin.
Also recommended that you use serverconnectedevent.
But this is no longer necessary

**Comment by GWServer** [comment]
The problem is still there.
Can you see what they changed in the plugin? It is open source
https://github.com/2lstudios-mc/FlameCord
I think that the MoveMeNow plugin now cannot determine that the player has left the server. The developer of the FlameCord plugin says that they changed the events that used to kick the player out of the server in order to avoid errors in the console when attacking the server.

I will describe what the problem is:
When a player leaves the server (not from the lobby), the MoveMeNow plugin tries to move this player to the lobby, which causes problems with other plugins
mode: blacklist

**Comment by GWServer** [comment]
I added "Server connection was lost" to the list and the problem disappeared.

mode: blacklist
list:
- "Lost connection to server-"

There are no problems in this mode.
mode: whitelist
